# -*- coding: utf-8 -*-
"""Progetto_programmazione_con_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orbF9bpkWODYU-NapQu872VaQRRWng0b

Prgetto strutturato con programmazione ad oggetti, pensato separando la rappresentazione del contatto dalla gestione della rubrica.
Aggiunta validazione dei dati, ricerca, modifica, eliminazione e persistenza su file JSON. I dati vengono in definitiva caricati automaticamente all’avvio e salvati dopo ogni operazione che modifica la rubrica.
"""

import json

def valida_nome(nome):
    return nome.replace(" ", "").isalpha()


def valida_telefono(telefono):
    return telefono.isdigit()


def valida_email(email):
    return "@" in email

# ============================================================
# CLASSE CONTATTO
# ============================================================

class Contatto:
    def __init__(self, nome, cognome, telefono, email):
        self.nome = nome
        self.cognome = cognome
        self.telefono = telefono
        self.email = email

    def visualizza(self):
        print(f"Nome: {self.nome}")
        print(f"Cognome: {self.cognome}")
        print(f"Telefono: {self.telefono}")
        print(f"Email: {self.email}")

    def modifica(self, nome, cognome, telefono, email):
        self.nome = nome
        self.cognome = cognome
        self.telefono = telefono
        self.email = email

    def to_dict(self):
        return {
            "nome": self.nome,
            "cognome": self.cognome,
            "telefono": self.telefono,
            "email": self.email
        }


# ============================================================
# CLASSE RUBRICA
# ============================================================

class Rubrica:
    def __init__(self):
        self.contatti = []

    # Aggiunge un contatto
    def aggiungi(self, contatto):
        self.contatti.append(contatto)

    # Visualizza tutti i contatti
    def visualizza(self):
        if len(self.contatti) == 0:
            print("\nLa rubrica è vuota.")
            return

        print("\n===== CONTATTI =====")

        for i, contatto in enumerate(self.contatti, start=1):
            print(f"\n--- Contatto {i} ---")
            contatto.visualizza()

    # Cerca un contatto per nome o cognome
    def cerca(self, testo):
        risultati = []

        for contatto in self.contatti:
            if (testo.lower() in contatto.nome.lower() or
                    testo.lower() in contatto.cognome.lower()):
                risultati.append(contatto)

        return risultati

    # Elimina un contatto
    def elimina(self, contatto):
        self.contatti.remove(contatto)

    # Salva i contatti in un file JSON
    def salva(self, nome_file):
        dati = []

        for contatto in self.contatti:
            dati.append(contatto.to_dict())

        with open(nome_file, "w", encoding="utf-8") as file:
            json.dump(dati, file, indent=4, ensure_ascii=False)

    # Carica i contatti da un file JSON
    def carica(self, nome_file):
        try:
            with open(nome_file, "r", encoding="utf-8") as file:
                dati = json.load(file)

            self.contatti = []

            for elemento in dati:
                contatto = Contatto(
                    elemento["nome"],
                    elemento["cognome"],
                    elemento["telefono"],
                    elemento["email"]
                )

                self.contatti.append(contatto)

            return True

        except FileNotFoundError:
            return False


# ============================================================
# FUNZIONI DEL PROGRAMMA
# ============================================================

def aggiungi_contatto(rubrica):
    print("\n===== AGGIUNGI CONTATTO =====")

    # Controllo nome
    while True:
        nome = input("Nome: ")

        if valida_nome(nome):
            break
        else:
            print("Errore: il nome deve contenere solo lettere.")

    # Controllo cognome
    while True:
        cognome = input("Cognome: ")

        if valida_nome(cognome):
            break
        else:
            print("Errore: il cognome deve contenere solo lettere.")

    # Controllo telefono
    while True:
        telefono = input("Telefono: ")

        if valida_telefono(telefono):
            break
        else:
            print("Errore: il telefono deve contenere solo numeri.")

    # Controllo email
    while True:
        email = input("Email: ")

        if valida_email(email):
            break
        else:
            print("Errore: l'email deve contenere il carattere @.")

    nuovo_contatto = Contatto(nome, cognome, telefono, email)

    rubrica.aggiungi(nuovo_contatto)

    # Salvataggio automatico
    rubrica.salva("contatti.json")

    print("\nContatto aggiunto e salvato con successo!")

def visualizza_contatti(rubrica):
    rubrica.visualizza()

def modifica_contatto(rubrica):
    print("\n===== MODIFICA CONTATTO =====")

    testo = input("Inserisci nome o cognome del contatto da modificare: ")

    risultati = rubrica.cerca(testo)

    if len(risultati) == 0:
        print("Nessun contatto trovato.")
        return

    # Se vengono trovati più contatti
    if len(risultati) > 1:
        print("\nSono stati trovati più contatti:")

        for i, contatto in enumerate(risultati, start=1):
            print(
                f"{i}. {contatto.nome} "
                f"{contatto.cognome} - "
                f"{contatto.telefono}"
            )

        try:
            scelta = int(input("Quale vuoi modificare? "))

            if scelta < 1 or scelta > len(risultati):
                print("Scelta non valida.")
                return

            contatto = risultati[scelta - 1]

        except ValueError:
            print("Devi inserire un numero.")
            return

    else:
        contatto = risultati[0]

    print("\nInserisci i nuovi dati.")
    print("Premi INVIO per mantenere il valore precedente.")

    # =========================
    # CONTROLLO NOME
    # =========================

    while True:
        nome = input(f"Nome [{contatto.nome}]: ")

        if nome == "":
            nome = contatto.nome
            break

        if valida_nome(nome):
            break

        print("Errore: il nome deve contenere solo lettere.")

    # =========================
    # CONTROLLO COGNOME
    # =========================

    while True:
        cognome = input(f"Cognome [{contatto.cognome}]: ")

        if cognome == "":
            cognome = contatto.cognome
            break

        if valida_nome(cognome):
            break

        print("Errore: il cognome deve contenere solo lettere.")

    # =========================
    # CONTROLLO TELEFONO
    # =========================

    while True:
        telefono = input(f"Telefono [{contatto.telefono}]: ")

        if telefono == "":
            telefono = contatto.telefono
            break

        if valida_telefono(telefono):
            break

        print("Errore: il telefono deve contenere solo numeri.")

    # =========================
    # CONTROLLO EMAIL
    # =========================

    while True:
        email = input(f"Email [{contatto.email}]: ")

        if email == "":
            email = contatto.email
            break

        if valida_email(email):
            break

        print("Errore: l'email deve contenere il carattere @.")

    # Modifica effettiva del contatto
    contatto.modifica(nome, cognome, telefono, email)

    # Salvataggio automatico
    rubrica.salva("contatti.json")

    print("\nContatto modificato e salvato con successo!")

def elimina_contatto(rubrica):
    print("\n===== ELIMINA CONTATTO =====")

    testo = input("Inserisci nome o cognome del contatto da eliminare: ")

    risultati = rubrica.cerca(testo)

    if len(risultati) == 0:
        print("Nessun contatto trovato.")
        return

    if len(risultati) > 1:
        print("\nSono stati trovati più contatti:")

        for i, contatto in enumerate(risultati, start=1):
            print(
                f"{i}. {contatto.nome} "
                f"{contatto.cognome} - "
                f"{contatto.telefono}"
            )

        try:
            scelta = int(input("Quale vuoi eliminare? "))

            if scelta < 1 or scelta > len(risultati):
                print("Scelta non valida.")
                return

            contatto = risultati[scelta - 1]

        except ValueError:
            print("Devi inserire un numero.")
            return

    else:
        contatto = risultati[0]

    conferma = input(
        f"Sei sicuro di voler eliminare "
        f"{contatto.nome} {contatto.cognome}? (s/n): "
    )

    if conferma.lower() == "s":
        rubrica.elimina(contatto)
        print("Contatto eliminato con successo!")
        salva_contatti(rubrica)
    else:
        print("Operazione annullata.")


def cerca_contatto(rubrica):
    print("\n===== CERCA CONTATTO =====")

    testo = input("Inserisci nome o cognome da cercare: ")

    risultati = rubrica.cerca(testo)

    if len(risultati) == 0:
        print("Nessun contatto trovato.")
        return

    print(f"\nTrovati {len(risultati)} contatti:")

    for i, contatto in enumerate(risultati, start=1):
        print(f"\n--- Risultato {i} ---")
        contatto.visualizza()


def salva_contatti(rubrica):
    nome_file = "contatti.json"

    rubrica.salva(nome_file)

    print(f"\nContatti salvati nel file '{nome_file}'.")


def carica_contatti(rubrica):
    nome_file = "contatti.json"

    if rubrica.carica(nome_file):
        print(f"\nContatti caricati dal file '{nome_file}'.")
    else:
        print("\nIl file dei contatti non esiste ancora.")


# ============================================================
# MENU PRINCIPALE
# ============================================================

def menu(rubrica):

    while True:

        print("\n")
        print("===================================")
        print("       CONTACTEASE SOLUTIONS       ")
        print("===================================")
        print("1. Aggiungi contatto")
        print("2. Visualizza contatti")
        print("3. Modifica contatto")
        print("4. Elimina contatto")
        print("5. Cerca contatto")
        print("6. Carica contatti")
        print("0. Esci")
        print("===================================")

        scelta = input("Scegli un'opzione: ")

        if scelta == "1":
            aggiungi_contatto(rubrica)

        elif scelta == "2":
            visualizza_contatti(rubrica)

        elif scelta == "3":
            modifica_contatto(rubrica)

        elif scelta == "4":
            elimina_contatto(rubrica)

        elif scelta == "5":
            cerca_contatto(rubrica)

        elif scelta == "6":
            carica_contatti(rubrica)

        elif scelta == "0":
            print("\nProgramma terminato. Arrivederci!")
            break

        else:
            print("\nScelta non valida. Riprova.")


# ============================================================
# FUNZIONE MAIN
# ============================================================

def main():

    rubrica = Rubrica()

    # Caricamento automatico all'avvio
    if rubrica.carica("contatti.json"):
        print("Contatti caricati automaticamente.")
    else:
        print("Nessun file di contatti trovato.")
        print("È stata creata una nuova rubrica.")

    menu(rubrica)


# ============================================================
# AVVIO DEL PROGRAMMA
# ============================================================

if __name__ == "__main__":
    main()















